openapi: "3.0.1"
info:
  title: "SunairioAPI"
  version: "2021-02-01"
servers:
- url: "https://sunairio-api.com/{basePath}"
  variables:
    basePath:
      default: "/v1"
paths:
  /rawfile:
    get:
      description: "Raw Simulations"
      parameters:
      - name: "fcstDate"
        in: "query"
        schema:
          type: "string"
      - name: "feature"
        in: "query"
        schema:
          type: "string"
      - name: "loc"
        in: "query"
        schema:
          type: "string"
      - name: "tz"
        in: "query"
        schema:
          type: "string"
      - name: "cycle"
        in: "query"
        schema:
          type: "string"
      - name: "apiKey"
        in: "query"
        schema:
          type: "string"
      - name: "agg"
        in: "query"
        schema:
          type: "string"
      - name: "timeFmt"
        in: "query"
        schema:
          type: "string"
      - name: "freq"
        in: "query"
        schema:
          type: "string"
      responses:
        200:
          description: "200 response"
          content:
            text/csv:
              schema:
                $ref: "#/components/schemas/Empty"
      security:
      - api_key: []
  /fcstpct:
    get:
      description: "Simulation Percentiles"
      parameters:
      - name: "feature"
        in: "query"
        description: "forecast feature: 'tmp', e.g."
        required: true
        schema:
          type: "string"
      - name: "fcstDate"
        in: "query"
        description: "YYYYMMDD or blank for current"
        schema:
          type: "string"
      - name: "fmt"
        in: "query"
        description: "response format: 'html' or 'csv'"
        schema:
          type: "string"
      - name: "cols"
        in: "query"
        description: "columns to display, comma-separated numbers like '1,3,4'"
        schema:
          type: "string"
      - name: "loc"
        in: "query"
        description: "ICAO code or 'ercot'"
        schema:
          type: "string"
      - name: "tz"
        in: "query"
        description: "timezone: 'CPT' for Central Prevailing Time"
        schema:
          type: "string"
      - name: "cycle"
        in: "query"
        description: "UTC hour that simulation was run. If fcstDate is blank, always\
          \ returns latest run. Otherwise returns earliest of an historical date.\
          \ Does not necessarily correspond to GFS/Euro schedule"
        schema:
          type: "string"
      - name: "apiKey"
        in: "query"
        description: "unique identifier required for authentication"
        required: true
        schema:
          type: "string"
      - name: "pct"
        in: "query"
        description: "forecast percentiles. comma-separated numbers from 1-99 and\
          \ 'mean' For example '5,25,75,mean'"
        required: true
        schema:
          type: "string"
      - name: "timeFmt"
        in: "query"
        description: "blank for default time format or 'iso' for ISO 8601"
        schema:
          type: "string"
      - name: "agg"
        in: "query"
        description: "aggregation method for time resampling. 'mean', 'min', 'max',\
          \ 'sum'"
        schema:
          type: "string"
      - name: "freq"
        in: "query"
        description: "'h' for hourly, 'd' for daily"
        schema:
          type: "string"
      responses:
        200:
          description: "200 response"
          content:
            text/csv:
              schema:
                $ref: "#/components/schemas/Empty"
            text/html:
              schema:
                $ref: "#/components/schemas/Empty"
      security:
      - api_key: []
  /fcst:
    get:
      description: "Simulation Percentiles. DEPRECATED"
      parameters:
      - name: "feature"
        in: "query"
        schema:
          type: "string"
      - name: "fcstDate"
        in: "query"
        description: "YYYYMMDD or blank for current"
        schema:
          type: "string"
      - name: "fmt"
        in: "query"
        schema:
          type: "string"
      - name: "cols"
        in: "query"
        schema:
          type: "string"
      - name: "loc"
        in: "query"
        description: "ICAO code or 'ercot'"
        schema:
          type: "string"
      - name: "quantile"
        in: "query"
        schema:
          type: "string"
      - name: "tz"
        in: "query"
        schema:
          type: "string"
      - name: "cycle"
        in: "query"
        schema:
          type: "string"
      - name: "apiKey"
        in: "query"
        required: true
        schema:
          type: "string"
      - name: "timeFmt"
        in: "query"
        schema:
          type: "string"
      - name: "agg"
        in: "query"
        schema:
          type: "string"
      - name: "freq"
        in: "query"
        description: "'h' for hourly, 'd' for daily"
        schema:
          type: "string"
      responses:
        200:
          description: "200 response"
          content:
            text/csv:
              schema:
                $ref: "#/components/schemas/Empty"
            text/html:
              schema:
                $ref: "#/components/schemas/Empty"
      security:
      - api_key: []
  /project:
    get:
      description: "Custom Project Data"
      parameters:
      - name: "feature"
        in: "query"
        schema:
          type: "string"
      - name: "fmt"
        in: "query"
        schema:
          type: "string"
      - name: "loc"
        in: "query"
        schema:
          type: "string"
      - name: "projName"
        in: "query"
        schema:
          type: "string"
      - name: "tz"
        in: "query"
        schema:
          type: "string"
      - name: "apiKey"
        in: "query"
        required: true
        schema:
          type: "string"
      - name: "timeFmt"
        in: "query"
        schema:
          type: "string"
      - name: "freq"
        in: "query"
        schema:
          type: "string"
      - name: "marksDate"
        in: "query"
        schema:
          type: "string"
      - name: "bucket"
        in: "query"
        schema:
          type: "string"
      - name: "version"
        in: "query"
        schema:
          type: "string"
      security:
      - api_key: []
components:
  schemas:
    Empty:
      title: "Empty Schema"
      type: "object"
  securitySchemes:
    api_key:
      type: "apiKey"
